blank_issues_enabled: false
contact_links:
    - name: Jinmaocuicuisha-plugin 帮助中心
      url: https://gitee.com/JMCCS/jinmaocuicuisha/blob/master/Plugin%20function.md
      about: 提供 Jinmaocuicuisha-plugin  基本功能使用、介绍和常见问题解答